// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20250511100948_Added_LoaiNhom")]
    partial class Added_LoaiNhom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_DonViTinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHetHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DonViTinhs");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_HangHoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DacTinh")
                        .HasColumnType("text");

                    b.Property<Guid?>("DonViTinhId")
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("MaMatHang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHetHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NhomHangHoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenMatHang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("NhomHangHoaId");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<int>("LoaiNhom")
                        .HasColumnType("integer");

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NhomChaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NhomChaId");

                    b.ToTable("NhomHangHoa");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_HangHoa", b =>
                {
                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_DonViTinh", "DonViTinh")
                        .WithMany("HangHoas")
                        .HasForeignKey("DonViTinhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", "NhomHangHoa")
                        .WithMany("HangHoas")
                        .HasForeignKey("NhomHangHoaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonViTinh");

                    b.Navigation("NhomHangHoa");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", b =>
                {
                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", "NhomCha")
                        .WithMany("NhomCon")
                        .HasForeignKey("NhomChaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NhomCha");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_DonViTinh", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", b =>
                {
                    b.Navigation("HangHoas");

                    b.Navigation("NhomCon");
                });
#pragma warning restore 612, 618
        }
    }
}
