// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20250618105026_AddedDb")]
    partial class AddedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_DonViTinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHetHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_HangHoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DacTinh")
                        .HasColumnType("text");

                    b.Property<Guid?>("DonViTinhId")
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHangHoa")
                        .HasColumnType("boolean");

                    b.Property<string>("MaMatHang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHetHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NhomHangHoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenMatHang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("NhomHangHoaId");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_HangHoaThiTruong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DacTinh")
                        .HasColumnType("text");

                    b.Property<Guid?>("DonViTinhId")
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<int>("LoaiMatHang")
                        .HasColumnType("integer");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MatHangChaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHetHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ThuocTinhId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("IsDelete");

                    b.HasIndex("LoaiMatHang");

                    b.HasIndex("MatHangChaId");

                    b.HasIndex("ThuocTinhId");

                    b.HasIndex("Ma", "MatHangChaId")
                        .IsUnique();

                    b.ToTable("Dm_HangHoaThiTruong");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_LoaiGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("LoaiGias");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHetHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NhomChaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NhomChaId");

                    b.ToTable("NhomHangHoa");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_ThuocTinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanChinhCot")
                        .HasColumnType("text");

                    b.Property<string>("CongThuc")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DinhDang")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<int>("Loai")
                        .HasColumnType("integer");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHetHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ThuocTinhChaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Width")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ThuocTinhChaId");

                    b.ToTable("Dm_ThuocTinh");
                });

            modelBuilder.Entity("Core.Entities.Domain.NghiepVu.ThuThapGiaThiTruong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HangHoaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoaiGiaId")
                        .HasColumnType("uuid");

                    b.Property<int>("LoaiNghiepVu")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayThuThap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HangHoaId");

                    b.HasIndex("IsDelete");

                    b.HasIndex("LoaiGiaId");

                    b.HasIndex("LoaiNghiepVu");

                    b.HasIndex("NgayThuThap");

                    b.HasIndex("NgayThuThap", "HangHoaId", "LoaiGiaId", "LoaiNghiepVu")
                        .IsUnique();

                    b.ToTable("ThuThapGiaThiTruongs");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_HangHoa", b =>
                {
                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_DonViTinh", "DonViTinh")
                        .WithMany("HangHoas")
                        .HasForeignKey("DonViTinhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", "NhomHangHoa")
                        .WithMany("HangHoas")
                        .HasForeignKey("NhomHangHoaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonViTinh");

                    b.Navigation("NhomHangHoa");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_HangHoaThiTruong", b =>
                {
                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_DonViTinh", "DonViTinh")
                        .WithMany("MatHangs")
                        .HasForeignKey("DonViTinhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_HangHoaThiTruong", "MatHangCha")
                        .WithMany("MatHangCon")
                        .HasForeignKey("MatHangChaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_ThuocTinh", "ThuocTinh")
                        .WithMany("HangHoaThiTruongs")
                        .HasForeignKey("ThuocTinhId");

                    b.Navigation("DonViTinh");

                    b.Navigation("MatHangCha");

                    b.Navigation("ThuocTinh");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", b =>
                {
                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", "NhomCha")
                        .WithMany("NhomCon")
                        .HasForeignKey("NhomChaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NhomCha");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_ThuocTinh", b =>
                {
                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_ThuocTinh", "ThuocTinhCha")
                        .WithMany("ThuocTinhCon")
                        .HasForeignKey("ThuocTinhChaId");

                    b.Navigation("ThuocTinhCha");
                });

            modelBuilder.Entity("Core.Entities.Domain.NghiepVu.ThuThapGiaThiTruong", b =>
                {
                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_HangHoaThiTruong", "HangHoa")
                        .WithMany("ThuThapGiaThiTruongs")
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.Domain.DanhMuc.Dm_LoaiGia", "LoaiGia")
                        .WithMany("ThuThapGiaThiTruongs")
                        .HasForeignKey("LoaiGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("LoaiGia");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_DonViTinh", b =>
                {
                    b.Navigation("HangHoas");

                    b.Navigation("MatHangs");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_HangHoaThiTruong", b =>
                {
                    b.Navigation("MatHangCon");

                    b.Navigation("ThuThapGiaThiTruongs");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_LoaiGia", b =>
                {
                    b.Navigation("ThuThapGiaThiTruongs");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_NhomHangHoa", b =>
                {
                    b.Navigation("HangHoas");

                    b.Navigation("NhomCon");
                });

            modelBuilder.Entity("Core.Entities.Domain.DanhMuc.Dm_ThuocTinh", b =>
                {
                    b.Navigation("HangHoaThiTruongs");

                    b.Navigation("ThuocTinhCon");
                });
#pragma warning restore 612, 618
        }
    }
}
